[build]
  command = "npm run build"
  publish = "apps/client/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval'; img-src 'self' data: https:; media-src 'self' data: https:; connect-src 'self' https:;"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
